all:
	@echo "make (up|down)"

down:
	scp gandalf:rfutil gandalf:rfutil.inc.php .

up:
	scp rfutil rfutil.inc.php sargas:
	scp rfutil rfutil.inc.php titan:
	scp rfutil rfutil.inc.php pollux:
	scp rfutil rfutil.inc.php miranda:
